version: "3.8"

services:
  server:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    depends_on:
      - client

  client:
    build:
      context: ./Frontend/nameless
    ports:
      - "3000:3000"